import type { Metadata } from 'next'
import { PT_Mono } from 'next/font/google'
import './globals.css'

const ptMono = PT_Mono({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ptMono.className}>{children}</body>
    </html>
  )
};
